---
- name: setup.yml
  hosts: all
  gather_facts: yes

  roles:
    - role: python3-install
      tags:
        - never

  post_tasks:
    - name: Install Ansible
      ansible.builtin.pip:
        name: ansible
        executable: "pip{{ python3_version | regex_search('3\\.[0-9]+') }}"
        extra_args: --user

    - name: Gather the packages facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Debug packages
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages }}"

    - name: Install Terraform
      block:
        - name: Install yum-utils
          ansible.builtin.yum:
            name: yum-utils
            state: latest

        - name: Add Official HashiCorp Linux repo
          ansible.builtin.command:
            cmd: "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"

        - name: Install terraform from the new repo
          ansible.builtin.yum:
            name: terraform
            state: latest
      when: "'terraform' not in ansible_facts.packages"
      become: yes

    - name: Install Packer
      block:
        - name: Install yum-utils
          ansible.builtin.yum:
            name: yum-utils
            state: latest

        - name: Add Official HashiCorp Linux repo
          ansible.builtin.command:
            cmd: "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"

        - name: Install packer from the new repo
          ansible.builtin.yum:
            name: packer
            state: latest
      when: "'packer' not in ansible_facts.packages"
      become: yes

